Ryo0417/team_hks

src/ejs/component/_c-category-list.ejs, src/sass/object/project/_p-category-list.scss
=> Create category list

src/ejs/component/_c-pagination-prev-next.ejs, src/sass/object/project/_p-paginaiton-prev-next.scss
=> Create pagination prevnext

src/ejs/component/_c-btn.ejs, src/ejs/component/_c-work-card.ejs, src/ejs/component/_c-work-cards.ejs, src/sass/object/component/_c-btn.scss, src/sass/object/component/_c-work-card.scss, src/sass/object/component/_c-work-cards.scss
=> Create work card

src/ejs/component/_c-related-work-card.ejs, src/ejs/component/_c-related-work-cards.ejs, src/sass/object/component/_c-related-work-card.scss, src/sass/object/component/_c-related-work-cards.scss
=> Create work related card

src/ejs/component/_c-related-card-title.ejs, src/sass/object/component/_c-related-card-title.scss
=> 関連記事タイトルの作成

src/ejs/project/_p-news-item.ejs, src/ejs/project/_p-news-items.ejs, src/sass/object/project/_p-news-item.scss
=> お知らせ（下層ページ）アイテムの作成

src/ejs/index.ejs, src/ejs/project/_p-common-contact.ejs
index.ejsのお問い合わせパーツ読み込みの入れ子構造修正
=> _p-common-contact.ejs入れ子構造修正

src/ejs/project/_p-related-work-cards.ejs, src/ejs/project/_p-sub-work-cards.ejs, src/ejs/project/_p-work-card.ejs
=> 制作実績カードの修正（MTG内容反映）

src/ejs/component/_c-category-item.ejs, src/ejs/component/_c-category-list.ejs, src/sass/object/component/_c-category-list.scss
=> Fix category list

src/ejs/component/_c-category-item.ejs, src/ejs/component/_c-category-list.ejs, src/js/script.js
=> カテゴリリストにjQuery付与

src/ejs/news.ejs, src/sass/object/component/_c-pagination.scss, src/sass/object/project/_p-sub-news.scss
news.ejsの新規作成
p-sub-news.scssの新規作成
=> 下層ニュースページの作成

src/ejs/content.ejs, src/ejs/project/_p-sub-content-card.ejs, src/ejs/project/_p-sub-content.ejs, src/ejs/project/_p-sub-contents.ejs, src/sass/object/layout/_l-sub-content.scss, src/sass/object/project/_p-sub-content-card.scss, src/sass/object/project/_p-sub-content.scss, src/sass/object/project/_p-sub-contents.scss
content.ejsの作成
p-sub-content→p-sub-content-cardにクラス名を修正
その他レイアウト調整等
=> 事業内容下層ページの新規作成

src/ejs/blog.ejs, src/ejs/project/_p-sub-blog-cards.ejs, src/ejs/project/_p-top-blog-cards.ejs, src/sass/object/layout/_l-sub-blog.scss, src/sass/object/project/_p-sub-blog-cards.scss, src/sass/object/project/_p-sub-blog.scss
blog.ejsの修正
p-sub-blog-cardsの修正
scssの新規作成
=> ブログ下層ページの作成

src/ejs/component/_c-related-card-title.ejs
=> 関連部分のタイトル修正

src/ejs/component/_c-related-card-title.ejs, src/ejs/single-blog.ejs
=> 記事詳細ページの作成

src/sass/object/project/_p-top-blog-cards.scss
=> Revert "topブログセクション余白修正"

src/ejs/overview.ejs, src/ejs/project/_p-sub-overview-item.ejs, src/ejs/project/_p-sub-overview-list.ejs, src/sass/object/project/_p-map.scss, src/sass/object/project/_p-sub-overivew.scss, src/sass/object/project/_p-sub-overview-item.scss, src/sass/object/project/_p-sub-overview-list.scss
overview.ejsの作成
事業概要リスト・アイテム用ejsの作成
マップ作成
=> 事業概要下層ページの作成

src/sass/object/component/_c-category-item.scss, src/sass/object/component/_c-category-list.scss, src/sass/object/layout/_l-single-blog.scss, src/sass/object/project/_p-work-card.scss
=> ブログ詳細記事ページ上部余白の修正

src/sass/object/project/_p-work-card.scss
=> 制作実績カードのインナー幅修正

src/sass/object/layout/_l-sub-overview.scss
=> 企業概要ページのレイアウト調整

src/sass/object/project/_p-top-overview.scss
=> Top横スクロール修正

src/ejs/news.ejs, src/sass/object/project/_p-sub-news.scss
=> 下層ニュースページの修正

src/ejs/news.ejs, src/js/script.js, src/sass/object/project/_p-sub-news.scss
=> ヘッダー背景透過の修正

src/ejs/content.ejs, src/ejs/overview.ejs, src/ejs/project/_p-footer.ejs, src/ejs/project/_p-sub-content-card.ejs, src/ejs/project/_p-sub-contents.ejs, src/ejs/project/_p-sub-overview-list.ejs, src/sass/object/project/_p-footer.scss, src/sass/object/project/_p-sub-overview-item.scss, src/sass/object/project/_p-sub-overview-list.scss
=> 事業概要ページの修正（追加）

src/ejs/content.ejs, src/ejs/project/_p-footer.ejs, src/ejs/project/_p-sub-content-card.ejs, src/ejs/project/_p-sub-contents.ejs, src/sass/object/project/_p-footer.scss
=> 事業内容ページの修正

src/ejs/content.ejs, src/ejs/project/_p-footer.ejs, src/ejs/project/_p-sub-content-card.ejs, src/ejs/project/_p-sub-contents.ejs, src/ejs/project/_p-sub-overview-list.ejs, src/sass/object/project/_p-footer.scss, src/sass/object/project/_p-sub-overview-item.scss, src/sass/object/project/_p-sub-overview-list.scss
=> 事業概要ページの修正

src/sass/object/project/_p-map.scss, src/sass/object/project/_p-sub-overview-item.scss
=> 企業概要アイテムの修正

src/ejs/overview.ejs, src/ejs/project/_p-map.ejs, src/sass/object/project/_p-map.scss, src/sass/object/project/_p-sub-overview-item.scss
=> p-map.ejsの作成

src/ejs/overview.ejs, src/ejs/project/_p-map.ejs, src/sass/object/project/_p-map.scss, src/sass/object/project/_p-sub-blog-cards.scss, src/sass/object/project/_p-sub-blog.scss, src/sass/object/project/_p-sub-overview-item.scss
=> カテゴリリストの位置調整

src/ejs/overview.ejs, src/ejs/project/_p-map.ejs, src/sass/object/project/_p-blog-card.scss, src/sass/object/project/_p-map.scss, src/sass/object/project/_p-sub-blog-cards.scss, src/sass/object/project/_p-sub-blog.scss, src/sass/object/project/_p-sub-overview-item.scss
=> ブログカードの文字間隔等を修正

src/ejs/project/_p-sub-overview-list.ejs
=> W3Cチェックに伴うエラー修正

src/ejs/single-blog.ejs, src/sass/object/project/_p-blog-article.scss
=> ブログ記事詳細ページの修正

src/ejs/component/_c-pagination-prev-next.ejs, src/ejs/single-blog.ejs, src/ejs/single-news.ejs, src/ejs/single-work.ejs, src/sass/object/project/_p-footer-nav.scss, src/sass/object/project/_p-footer.scss, src/sass/object/project/_p-related-blog-card.scss
=> フッターのクリック領域を修正

src/sass/object/project/_p-related-blog-card.scss
=> ブログ関連記事のスタイル修正

src/ejs/component/_c-pagination-prev-next.ejs, src/ejs/single-blog.ejs, src/ejs/single-news.ejs, src/ejs/single-work.ejs, src/sass/object/project/_p-related-blog-card.scss
一覧ページの条件分岐を追加
上記に伴うincludeの記述を修正
=> ページネーション（前後）の修正

src/ejs/project/_p-blog-card.ejs, src/ejs/project/_p-news-item.ejs, src/sass/object/project/_p-related-blog-card.scss
=> ブログカードのタイトルタグを条件分岐

src/sass/object/project/_p-related-blog-card.scss
=> 関連ブログカードを修正

src/ejs/project/_p-news-item.ejs, src/sass/object/project/_p-related-blog-card.scss
=> W3Cチェックに伴うタグ修正

src/js/script.js
=> アドレスバーの記述を修正

src/ejs/overview.ejs, src/ejs/project/_p-sub-overview-item.ejs, src/ejs/project/_p-sub-overview-list.ejs, src/sass/object/project/_p-sub-overview-list.scss
=> W3Cチェックのエラー対応

src/ejs/component/_c-btn.ejs, src/ejs/news.ejs, src/ejs/project/_p-sub-news.ejs, src/sass/object/layout/_l-breadcrumb.scss, src/sass/object/layout/_l-sub-news.scss, src/sass/object/project/_p-sub-news.scss
パンくず・ニュースリストをパーツ化
上記に伴いスタイルを修正
=> 下層お知らせページ修正（MTG内容反映）

src/ejs/blog.ejs, src/ejs/content.ejs, src/ejs/project/_p-sub-blog.ejs, src/ejs/project/_p-sub-content.ejs, src/sass/object/layout/_l-sub-blog.scss, src/sass/object/layout/_l-sub-content.scss, src/sass/object/project/_p-sub-blog.scss, src/sass/object/project/_p-sub-content-card.scss, src/sass/object/project/_p-sub-content.scss, src/sass/object/project/_p-sub-contents.scss
p-sub-content.ejsを作成
パンくずを修正
上記に伴いスタイルを修正
画像のサイズ・余白等を修正
=> 事業内容ページを修正（MTG内容反映）

src/ejs/blog.ejs, src/ejs/project/_p-sub-blog.ejs, src/sass/object/layout/_l-sub-blog.scss, src/sass/object/project/_p-sub-blog.scss
p-sub-blog.ejsを作成
パンくずを修正
上記に伴いスタイルを修正
=> 下層ブログページを修正（MTG内容反映）

src/ejs/overview.ejs, src/ejs/project/_p-sub-overview.ejs, src/sass/object/layout/_l-sub-overview.scss, src/sass/object/project/_p-map.scss, src/sass/object/project/_p-sub-overview.scss
p-sub-overview.ejsを作成
overview.ejsを修正
上記に伴うスタイル修正
ファイル名の誤記を修正（p-overview.scss）
=> 企業概要下層ページを修正（MTG内容反映）

src/ejs/component/_c-pagination-prev-next.ejs, src/ejs/component/_c-related-card-title.ejs, src/ejs/project/_p-related-blog.ejs, src/ejs/project/_p-single-blog.ejs, src/ejs/single-blog.ejs, src/sass/object/layout/_l-single-blog.scss, src/sass/object/layout/_l-single-breadcrumb.scss, src/sass/object/project/_p-single-blog.scss
ejsパーツを作成
パーツ分割に伴いスタイル・条件分岐を修正
パンくずリストの上部余白を修正
=> ブログ詳細ページを修正（MTG内容反映）

src/ejs/component/_c-btn.ejs, src/sass/object/component/_c-btn.scss
=> ボタン修正（MTG内容反映）

src/ejs/component/_c-btn.ejs, src/ejs/project/_p-sub-work-cards.ejs, src/sass/object/component/_c-btn.scss
=> 不要な条件分岐を削除

src/ejs/project/_p-work-article.ejs, src/ejs/single-news.ejs, src/js/script.js, src/sass/object/project/_p-single-news.scss, src/sass/object/project/_p-single-work.scss
p-single-work__title→p-work-article__title
不要なCSSを削除
=> 制作実績詳細ページのクラス名を修正

src/ejs/single-news.ejs, src/sass/object/project/_p-single-news.scss
l-single-breadcrumbに修正
scssの不要な記述を削除
=> ニュース詳細ページのパンくず記述を修正

src/sass/object/project/_p-related-blog-cards.scss
display:flex;→display:grid;に修正
=> firefox表示崩れを修正（関連ブログ記事）

src/ejs/component/_c-btn.ejs, src/ejs/component/_c-pagination-prev-next.ejs, src/ejs/component/_c-related-card-title.ejs, src/ejs/project/_p-common-contact.ejs, src/ejs/project/_p-related-blog.ejs, src/ejs/project/_p-related-work.ejs, src/ejs/project/_p-single-blog.ejs, src/ejs/project/_p-single-news.ejs, src/ejs/project/_p-single-work.ejs, src/sass/object/component/_c-paginaiton-prev-next.scss
=> 関連部分のタイトルを修正

src/ejs/component/_c-btn.ejs, src/ejs/component/_c-pagination-prev-next.ejs, src/ejs/project/_p-common-contact.ejs, src/ejs/project/_p-single-blog.ejs, src/ejs/project/_p-single-news.ejs, src/ejs/project/_p-single-work.ejs, src/sass/object/component/_c-paginaiton-prev-next.scss
=> ページネーション（前後）を修正

src/ejs/project/_p-related-blog-cards.ejs, src/ejs/project/_p-sub-overview-list.ejs, src/ejs/project/_p-sub-work-cards.ejs, src/ejs/project/_p-sub-work.ejs, src/sass/object/project/_p-news-list.scss, src/sass/object/project/_p-related-blog-cards.scss, src/sass/object/project/_p-related-blog.scss, src/sass/object/project/_p-sub-work-cards.scss
=> 企業概要ページを修正

src/sass/object/project/_p-news-list.scss
=> 下層お知らせページを修正

src/ejs/project/_p-sub-work-cards.ejs, src/ejs/project/_p-sub-work.ejs, src/sass/object/project/_p-news-list.scss, src/sass/object/project/_p-sub-work-cards.scss
=> 制作実績ページを修正

src/ejs/project/_p-related-blog-cards.ejs, src/ejs/project/_p-sub-work-cards.ejs, src/ejs/project/_p-sub-work.ejs, src/sass/object/project/_p-news-list.scss, src/sass/object/project/_p-related-blog-cards.scss, src/sass/object/project/_p-related-blog.scss, src/sass/object/project/_p-sub-work-cards.scss
list→items
display: flex; → display: grid;（Firefox崩れ対応）
上記以外のスタイルを修正
=> 関連ブログ記事を修正

src/ejs/project/_p-related-work-cards.ejs, src/ejs/project/_p-sub-work-cards.ejs, src/ejs/project/_p-sub-work.ejs, src/sass/object/project/_p-news-list.scss, src/sass/object/project/_p-related-work-cards.scss, src/sass/object/project/_p-related-work.scss, src/sass/object/project/_p-sub-work-cards.scss
display: flex; → display: grid;
list→items
不要な記述を削除
=> Firefoxの表示崩れを修正（関連制作）

src/ejs/project/_p-related-blog-card.ejs, src/ejs/project/_p-related-work-card.ejs, src/ejs/project/_p-related-work-cards.ejs, src/sass/object/project/_p-related-blog-card.scss, src/sass/object/project/_p-related-work-card.scss, src/sass/object/project/_p-single-work.scss
=> 関連制作カードのスタイルを修正

src/ejs/project/_p-related-blog-card.ejs, src/sass/object/project/_p-related-blog-card.scss
hover時にちらつきが出たため、記述を修正
※aタグを一番外に出して、aタグhover時の内容を記述
=> ブログ関連記事hover時のエラーを修正

src/sass/object/project/_p-blog-article.scss, src/sass/object/project/_p-news-article.scss
=> 記事詳細h2タグの余白を修正

src/ejs/component/_c-pagination.ejs, src/ejs/project/_p-single-work-detail.ejs, src/ejs/project/_p-single-work-details.ejs, src/sass/object/project/_p-single-work-detail.scss, src/sass/object/project/_p-single-work-details.scss
パーツ化を意識してクラス名等を修正
p-single-work-details.scssを新規作成（detailと区別）
=> 制作実績詳細ページを修正

src/ejs/404.ejs, src/ejs/blog.ejs, src/ejs/common/_p-footer.ejs, src/ejs/contact.ejs, src/ejs/content.ejs, src/ejs/index.ejs, src/ejs/news.ejs, src/ejs/overview.ejs, src/ejs/single-blog.ejs, src/ejs/single-news.ejs, src/ejs/single-work.ejs, src/ejs/thanks.ejs, src/ejs/work.ejs, src/sass/object/layout/_l-footer.scss, src/sass/object/project/_p-sub-contact.scss
問い合わせページのみl-footerを付与するよう条件分岐
上記に伴うスタイル等の修正
=> フッターの余白を修正
